# Generated by Django 5.2.7 on 2025-10-13 09:34

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(max_length=20, unique=True)),
                ('trade_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone_number', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('direction', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(default='Chile', max_length=2)),
                ('pay_conditions', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=8)),
                ('state', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('BLQ', 'Bloqueado')], max_length=3)),
            ],
        ),
    ]
