# Generated by Django 5.2.7 on 2025-10-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField(unique=True)),
                ('ean_upc', models.CharField(blank=True, max_length=13, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=30)),
                ('uom_purchase', models.CharField(max_length=10)),
                ('uom_sale', models.CharField(max_length=10)),
                ('conversion_factor', models.BooleanField(default=True)),
                ('price', models.IntegerField(blank=True)),
                ('iva_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_stock', models.IntegerField(default=0)),
                ('maximum_stock', models.IntegerField(blank=True)),
                ('perishable', models.BooleanField(default=False)),
                ('batch_control', models.BooleanField(default=False)),
                ('series_control', models.BooleanField(default=False)),
                ('image_url', models.ImageField(blank=True, upload_to='')),
                ('datasheet_url', models.URLField(blank=True)),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('supplier', models.ManyToManyField(to='suppliers.supplier')),
            ],
        ),
    ]
