# Generated by Django 5.2.7 on 2025-10-13 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellar_name', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='movementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida'), ('ADJ', 'Ajuste'), ('DEVOL', 'Devolucion'), ('TRANS', 'Transferencia')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='inventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('batch', models.IntegerField(blank=True)),
                ('serie', models.IntegerField(blank=True)),
                ('caducity_date', models.DateField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('cellar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.cellar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.movementtype')),
            ],
        ),
    ]
