# Generated by Django 5.2.7 on 2025-10-13 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cellar',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='cellar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Modificacion'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Modificacion'),
        ),
        migrations.AddField(
            model_name='movementtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminacion'),
        ),
        migrations.AddField(
            model_name='movementtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Modificacion'),
        ),
    ]
